### ISSUE TITLE
AFL Video v1.8.1 Error

### ISSUE THREAD

**Issue by decasurf** [aussieaddons/plugin.video.afl-video#2565]
Received error message whilst trying to load live stream.

Error: 404 Client Error: Not Found for url:
https://api.telstra.com.v1/media-products/catalogues/media,

**Comment by pjconroy** [comment]
Me too

**Comment by glennguy** [comment]
I'll look into it, but first I need someone to supply a link to a debug
log. Instructions for that are here: http://kodi.wiki/view/Log_file/Easy

A quick checklist of things to try first though:
Make sure the appropriate subscription type is set in the add-on's settings
Make sure if you have a VPN or smart DNS service to turn it off
If you're using the free Telstra subscription, ensure that a service
eligible for the offer is linked to your Telstra id. You can check this by
logging in on a browser a telstra.com and checking the accounts in your
profile.

**Comment by easytiger17** [comment]
I uninstalled the add on and now I cannot reinstall. There appears to be some error message and I can catch CPythonInvoker... xbmc...???

**Comment by glennguy** [comment]
@easytiger17 in my experience, restarting Kodi should resolve
uninstalling/reinstalling issues

**Comment by easytiger17** [comment]
I have done that a couple of times now...??

**Comment by glennguy** [comment]
Can you supply a debug log? - instructions link in my post from earlier
today

**Comment by easytiger17** [comment]
Just tried to download kodi logfile uploader and it failed. Failed to install a dependancy

**Comment by easytiger17** [comment]
I'm using openelec with a raspberry Pi

**Comment by easytiger17** [comment]
I have a tva log uploader which allows me to enter my email address etc.. however, it fails also.

**Comment by glennguy** [comment]
@easytiger17  That's no good but unfortunately there's not much we can do without more info.

The one thing that I can think of that would cause all of this would be that you've run out of space on your SD card. It has happened to me before, can't remember exactly why but some sort of log file or database file had inadvertently filled it up.

**Comment by easytiger17** [comment]
The ares project have a Log uploader... the afl error shows in here...
[Kodi Log.txt](https://github.com/andybotting/xbmc-addon-afl-video/files/1118443/Kodi.Log.txt)

or this link....  https://ares-project.uk/logupload/log.php?id=1978930

**Comment by glennguy** [comment]
@easytiger17 
A few things:
Where are you sourcing the AFL addon from? It doesn't look like you have the repo installed for aussie addons. You can find instructions [here](https://github.com/xbmc-catchuptv-au/repo/). This will ensure you continue to receive updates and that it comes from us, not some other 3rd party repository. This could be an issue as from your log I get the error message ```ERROR: CAddonInstallJob[plugin.video.afl-video]: The dependency on xbmc.python version 2.25.0 could not be satisfied.``` which by itself is at odds with our current addon dependency requirements written in the source [here](https://github.com/andybotting/xbmc-addon-afl-video/blob/master/addon.xml#L3)

If trying to install from our repo doesn't help then we need a proper debug log: turn on debug logging in Kodi through settings menu, restart Kodi, recreate the problem and send log again. There's a lot more information in the log with debug logging turned on which could give us the info needed to pinpoint the problem.

**Comment by Mickhasone** [comment]
@glennguy 
Please check my log
https://paste.ubuntu.com/25009792/

THANKS

**Comment by glennguy** [comment]
@Mickhasone 
For yourself and anyone who is getting the 404 error message: The 404 error is caused by not having any eligible services attached to your Telstra ID supplied in the settings. The addon is supposed to display a dialog box with the message ```Please visit http://hub.telstra.com.au/sp2017-afl-app for further instructions to link your mobile service to the supplied Telstra ID``` but is not working correctly in the current version. There should be a new release soon that will address this, but this will not fix the underlying problem - you need to do that yourself. Visit the URL in a browser and follow the instructions to add your mobile account to your Telstra ID.

**Comment by Mickhasone** [comment]
@glennguy 
Thanks for your reply however my mobile service is linked to my telstra ID. I just done a test with the same details and did not have a problem with logging in on my ipad. Looking at the log I noticed that the telstra links are causing the problem. The following link to enter telstra ID account works properly:

https://signon.telstra.com/login?goto=https%3A%2F%2Fsignon.telstra.com%2Ffederation%2Fsaml2%3FSPID%3DAFLMedia%26furl%3Dhttp%253A%252F%252Fwww.afl.com.au%252Ftv-radio%252Fafl-on-telstra-tv%26curl%3Dhttp%253A%252F%252Fwww.afl.com.au%252Ftv-radio%252Fafl-on-telstra-tv&gotoNoTok=

I tried it on my browser and all is good.
How can we have this changed in the app?
THANKS

**Comment by glennguy** [comment]
@Mickhasone That link is for a paid subscription. Have you got the appropriate subscription type set in the addon's settings? My instructions in the last message have related to the free Live Pass subscription that most Telstra customers are entitled to as outlined here: https://www.telstra.com.au/tv-movies-music/sports-offer. The error message you're getting only comes from having the subscription type set to `Free Offer (Telstra ID)`.

Have you tried logging in via the link in my previous post?

**Comment by Mickhasone** [comment]
@glennguy 
Yes, when I log in I get the following:


Sorry

Home broadband customers are not eligible for this offer

Try to log in with another Telstra ID to link your mobile number
When I mentioned this to telstra, they directed me to the following link

https://signon.telstra.com/login?goto=https%3A%2F%2Fsignon.telstra.com%2Ffederation%2Fsaml2%3FSPID%3DAFLMedia%26furl%3Dhttp%253A%252F%252Fwww.afl.com.au%252Ftv-radio%252Fafl-on-telstra-tv%26curl%3Dhttp%253A%252F%252Fwww.afl.com.au%252Ftv-radio%252Fafl-on-telstra-tv&gotoNoTok=

This link works perfectly

**Comment by glennguy** [comment]
@Mickhasone 

That link lets me login perfectly fine, but when I go to watch a match replay it is asking for me to subscribe to a paid subscription.

It seems like they don't want users using the free subscription with a Telstra ID that is used for home broadband, for whatever reason. Which I know is frustrating but on the bright side we can use this nugget of information to help future users avoid this :)

What will work for you I believe (I hope!) is creating a new Telstra ID and linking your mobile to that. Sign out of telstra (or open a new incognito/private window) and go to http://hub.telstra.com.au/sp2017-afl-app again and give it a go. That link comes directly from within the app when you get your free sub via Telstra ID (rather than using the mobile network to verify)

**Comment by easytiger17** [comment]
Hi Glenguy.  Finally had a chance to sit down and have a look.   I put your afl link on a thumb and was able to download the addon but it doesn't work... Here is my log:

https://ares-project.uk/logupload/log.php?id=2017734

**Comment by andybotting** [comment]
@easytiger17 You're missing at least the BeautifulSoup4 dependency, which you would normally get if you installed from the repository. Did you follow the repository setup instructions?

http://aussieaddons.com/installation/

**Comment by easytiger17** [comment]
I actually just copied the zip file to a thumb and did it that way.  I will have a look later at the correct method.

**Comment by glennguy** [comment]
@easytiger17 you'll always run into problems if you simply unzip the zip file into the addons folder. You need to 'install from zip' within Kodi. Kodi looks at the addon's `addon.xml` file within the zip for any dependencies needed and will automatically install them as long as they're available from one of your installed repositories. Ideally though you should install the aussie addons repo as @andybotting mentioned which will give you automatic updates for the addon itself.
