### ISSUE TITLE
When trying to play, it says unable to find eligible services, it has been working in the past

### ISSUE THREAD

**Issue by s4m4ndo** [aussieaddons/plugin.video.afl-video#2582]

**Comment by glennguy** [comment]
Hi @s4m4ndo,

Have you cancelled any services recently or not recharged a pre paid linked to that Telstra ID? It is saying that there aren't any eligible services linked to that ID. If you're unsure, go to telstra.com and log in with your details and have a look in account settings to see what services you have linked.

**Comment by s4m4ndo** [comment]
i just checked and it states my plan is active, it is also working fine on my phone

**Comment by glennguy** [comment]
It usually works fine on the phone because it can confirm who you are using
the mobile network - the add-on can't do that.

What services are under your account? Is it just the mobile service or is
there home broadband or something else as well? I know other users have not
been able to claim the live pass on a Telstra id that has home broadband on
it.

One solution that always seems to work is to create a new Telstra ID and
link your mobile to it

**Comment by redline69** [comment]
This 'add-on' is a joke. Constant issues streaming live games.
Doesnt recognise my user id pr pwd for paid services either.
Either get it right or get rid of it!

**Comment by andybotting** [comment]
Thanks @redline69 for your "helpful" comments. 

Please keep in mind that we're building this stuff for free, and we're guessing our way through how Telstra/AFL's systems work to make this happen. We also have lots of people successfully using this add-on too.

We're more than happy to work with you to try and "get it right", which may help other users who might experience the same issues that you do.

**Comment by pcdeem** [comment]
Hey andybotting. Ignore the stupid comment from Mr ignorant there.
This addon rocks and has kept me from spending money on Foxtel ever since I found Kodi.
Keep chugging along.

Thanks

**Comment by pcdeem** [comment]
Hey andybotting. Ignore the stupid comment from Mr ignorant there.
This addon rocks and has kept me from spending money on Foxtel ever since I found Kodi.
Keep chugging along.

Thanks

**Comment by allly17** [comment]
I have a payed subscription and it’s not working either I need help
