### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by nuts65** [aussieaddons/plugin.video.afl-video#2584]
play.py (42) httperror: 403 client error forbidden for url
https://api.telstra.com/v1/media=commerce/orders
trying to get working on new imac
same login with kodi on windows pc works

**Comment by glennguy** [comment]
Hi @nuts65

Is your iMac running through a VPN or proxy by any chance?

**Comment by nuts65** [comment]
no it isn't

**Comment by andybotting** [comment]
Have you submitted an error report about this? You can do it though the add-on settings, and if you share the url it gives you, we might get some context around why this might be happening

**Comment by nuts65** [comment]
I did hit button to send error & will try find the url after work. Thx for reply

**Comment by nuts65** [comment]
https://gist.github.com/aussieaddonsbot/5fc3bf296e64a502c93bb34e3c163b93

**Comment by andybotting** [comment]
Thanks. Was able to match this up with your original error report https://github.com/xbmc-catchuptv-au/issue-reports/issues/995

Can't see anything obvious in there, but have noticed another report that looks similar, but from a Windows PC, so not specific to your OS then.

We might have to look into this a bit deeper.

**Comment by nuts65** [comment]
strange, NRL live working fine with same login in settings

**Comment by nuts65** [comment]
working now thankyou
