### ISSUE TITLE
AFL VIDEO V1.8.4 ERROR

### ISSUE THREAD

**Issue by whoopdad** [aussieaddons/plugin.video.afl-video#2590]
Play.py (41) - UnboundLocalErrir: local variable ‘res’ referenced before assignment.

Unsure what the above means and how I am able to fix it. Just attempting to watch replays of the tigers Premiership year!

**Comment by whoopdad** [comment]
Absolute legend!

Kind Regards,

Matthew Sealey
Licensed Estate Agent & Auctioneer
Barry Plant Real Estate
Manningham - Eltham - Whitehorse



On 5 Feb 2018, at 5:48 pm, Andy Botting <notifications@github.com<mailto:notifications@github.com>> wrote:


An update will be coming shortly to fix this up. Look out for v1.8.5

**Comment by glennguy** [comment]
Hi @whoopdad 

Could you try something for me? Go into the AFL Video settings menu (just select settings from the 'main' menu when you open the addon, and under the AFL Live Pass tab press enter/click on the 'Remove Stored Login Token' option. Then try watching videos again and let us know here if it fixes the issue or not. I've got a fairly good idea of what's wrong - I think your token has expired (and our code is failing before automatically removing it) - but I can't test it myself as I don't have that problem/can't reproduce.

Thanks heaps.

**Comment by whoopdad** [comment]
I am pressing the ‘remove stored login token’ button, however nothing is happening when I press it.

Kind Regards,

Matthew Sealey
Licensed Estate Agent & Auctioneer
Barry Plant Real Estate
Manningham - Eltham - Whitehorse



On 5 Feb 2018, at 9:09 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @whoopdad<https://github.com/whoopdad>

Could you try something for me? Go into the AFL Video settings menu (just select settings from the 'main' menu when you open the addon, and under the AFL Live Pass tab press enter/click on the 'Remove Stored Login Token' option. Then try watching videos again and let us know here if it fixes the issue or not. I've got a fairly good idea of what's wrong - I think your token has expired (and our code is failing before automatically removing it) - but I can't test it myself as I don't have that problem/can't reproduce.

Thanks heaps.

**Comment by glennguy** [comment]
yep that's normal.

Now try playing a video and it should *hopefully* work

Changes are incoming to rectify this in any case

**Comment by whoopdad** [comment]
It works!
You are a lifesaver. I can now watch the grand final an extra 50 times!

Kind Regards,

Matthew Sealey
Licensed Estate Agent & Auctioneer
Barry Plant Real Estate
Manningham - Eltham - Whitehorse



On 6 Feb 2018, at 2:21 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:

yep that's normal.

Now try playing a video and it should *hopefully* work

Changes are incoming to rectify this in any case
