### ISSUE TITLE
AFLVideo addon 18.4 not starting on Kodi 17.6 

### ISSUE THREAD

**Issue by afung1t** [aussieaddons/plugin.video.afl-video#2591]
Have not used the addon since after 2017 seasons end but now found it unable to start at all. Have download repos again and un-install/re-install but error is the same. I have attached the Kodi log for reference. Any help is much appreciated.

[kodi.log](https://github.com/aussieaddons/plugin.video.afl-video/files/1693556/kodi.log)

**Comment by glennguy** [comment]
Hi @afung1t

It looks like you're missing some dependencies for our addons they should
normally be automatically installed when installing afl-video, and the
installation would fail if they aren't. I can see that you have some other
repos installed - In our experience there's a lot of other repos that can
cause issues with the dependencies being installed. Try disabling the other
repos (except the official kodi one, not sure if that can be disabled
anyway - some of the dependencies come from there) and
uninstalling/reinstalling afl-video again.

**Comment by afung1t** [comment]
Hi,
I disabled all the repos as suggested and uninstall/reinstall the add-on  but to no avail. As a last resort, I restored  Kodi from a 2 MTH old backup,  Aussie add-on and others then updated itself and it looks like working again. I still don't know what caused the problem but thanks anyway for helping out. Cheers.
