### ISSUE TITLE
AFL Video Addon 1.8.4 Error

### ISSUE THREAD

**Issue by vlascot** [aussieaddons/plugin.video.afl-video#2592]
Hi There I'm new to this forum
I tried to watch the AFL add on  but an 1.8.4 error appeared. It worked fine couple weeks ago.
I downloaded the zip file of the updated add on 1.8.4-1 and installed it.
Now I'm getting this error " AFL video v1.8.4-1 ga8c07f2 ERROR" 
Attached photo of error window.
Any feedback will be appreciated.
Thanks
Vlascot
![184error](https://user-images.githubusercontent.com/36148390/35791288-09d77db4-0a3f-11e8-851f-48f9b90b7250.jpg)

**Comment by glennguy** [comment]
Hi @vlascot 

Could you try something for me? Go into the AFL Video settings menu (just select settings from the 'main' menu when you open the addon, and under the AFL Live Pass tab press enter/click on the 'Remove Stored Login Token' option. Then try watching videos again and let us know here if it fixes the issue or not. I've got a fairly good idea of what's wrong - I think your token has expired (and our code is failing before automatically removing it) - but I can't test it myself as I don't have that problem/can't reproduce.

Thanks heaps.

**Comment by glennguy** [comment]
Hey that's great to hear!

Yes the next version should do things as they should be done. We have no idea how long the login token lasts for (I think in 2016 it was 30 days, it doesn't tell us now) so we just clear it whenever it doesn't like your token. When that happens it will still come up with an error and give you the option to report it, but the next time you go to play it should work again.

Thanks for your help!
