### ISSUE TITLE
AFL Video v1.8.5 error with Live Matches

### ISSUE THREAD

**Issue by fortalyst** [aussieaddons/plugin.video.afl-video#2595]
Heya,

I have AFL Live Pass and am getting the following error (attached image)
![image](https://user-images.githubusercontent.com/36783986/36626239-7b625366-1983-11e8-82ff-c51544afdbfd.png)

I can see live stream for AFLW which doesn't require live pass however there seems to be an issue with acquiring a user token.

**Comment by allly17** [comment]
Did you fix it as I am having the same problem

**Comment by andybotting** [comment]
@fortalyst I haven't been able to reproduce this. Can you send me an issue report (hint: in the add-on settings).

**Comment by fortalyst** [comment]
How I replicated the problem:

1: Go to match replays -> AFL 2018 JLT Series -> Round 1 -> JLT: Kangaroos v Demons Q1
2: Note the "obtaining user token" dialog box
3: Note the subsequent error message as raised in issue
4: Raised issue which can be found at https://github.com/aussieaddons/issue-reports/issues/2095

Thx for looking into this andybotting

**Comment by andybotting** [comment]
@fortalyst I can see you've got a few other repositories set up - which we generally see a lot of issues with. I know it's a bit of hassle, but any chance you could maybe backup your kodi user dir (/sdcard/data/Android/kodi I think) and start fresh?

**Comment by allly17** [comment]
Ok when I get home

**Comment by fortalyst** [comment]
@andybotting Can't find that directory. Found /sdcard/Android/data/org.xbmc.kodi/ but there's nothing in there. I have previously had issues with my microsd. Have uninstalled Kodi and reinstalled aussieaddons and AFL Video - this seems to have resolved my issue.

One thing I WILL mention now that you've made me think of it is that once upon a time I followed a guide to update a couple files within Kodi so that would automatically send its streams to LocalCast and subsequently chromecast to my tv without requiring stream processing on the phone. Would say it is quite possible that this could be a part of the problem. Before I go attempting to find that guide again, do you have any recommendations for how to set up chromecasting?

**Comment by andybotting** [comment]
@fortalyst There's a folder in /sdcard/Android/data/org.xbmc.kodi/ called '.files' - notice the dot at the front. This dot will cause the folder to be hidden, usually.

I've not done much like this around chromecasting. My main platform is Android TV at the moment, so running Kodi directly on the TV is much better :)

I'll close this ticket now. Thanks

**Comment by allly17** [comment]
Here is my issue 






Sent from my iPhone

**Comment by glennguy** [comment]
@fortalyst 

I've seen that error a bunch of times in our issue reports - could you do me a favor?

Go into Kodi's settings -> system -> add-ons -> manage dependencies, and tell me the version of 'requests' that you have installed?

Mine is showing 2.18.4.1

The error message you're seeing is related to an older version of requests that has been fixed. I can't be sure but my thinking is this is related to the 3rd party streaming repositories, the theory being that they may have their own bundled version of requests that is using the older version, *but* bundled for Kodi with a higher version number so it supersedes and installs over the current version.

Thanks for you help

Glenn

**Comment by fortalyst** [comment]
@glennguy Yep reckon the problem was likely to be along that path. I previously had the Exodus pack installed as well as a modification which I implemented which integrates Kodi with the LocalCast app so that stream processing is handled by the Chromecast rather than my phone. I suspect the issue may also have something to do with that given that fetching the live pass token would happen at the point where I'd expect a stream to load up localcast. 

Have reinstalled my Chromecasting fix so reckon the issue definitely belonged to the Exodus pack
