### ISSUE TITLE
AFL Video 1.8.5 stopped working

### ISSUE THREAD

**Issue by gbvluva** [aussieaddons/plugin.video.afl-video#2596]
Hi, was watching JLT when on Sunday it cut out during the 2nd Quarter of the Port v West Coast match and I got  this message.

- [ ] 
![img_20180225_220421046](https://user-images.githubusercontent.com/36826568/36647172-af1a66a0-1ad5-11e8-8ef7-7f56f0cb1641.jpg)
Love the add-on, would appreciate any help. Using Telstra login.

**Comment by allly17** [comment]
I can’t seem to get the subscription to work please help as the afl season is nearly here

**Comment by andybotting** [comment]
@gbvluva It suggests you're using a VPN/proxy. Maybe try turning that off?

@allly17 Would be really helpful if you could provide some details? There could be a whole range of reasons why it's not working for you.

**Comment by gbvluva** [comment]
Hi, I can now watch all replay content and AFL live tv again, I'll test again Wednesday night when the live match comes on. Hopefully just a glitch.

**Comment by andybotting** [comment]
@gbvluva Were you doing anything with VPNs or proxies?

**Comment by gbvluva** [comment]
No to be honest. Turned everything off including wi-fi and when I went back into it last night I could access  everything again as normal, with my VPN running. The proper test I suppose will be when trying the next live match. I had watched the 2 games Saturday and the first game Sunday without any issues.
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 27/2/18, 11:33 am Andy Botting <notifications@github.com> wrote:
@gbvluva Were you doing anything with VPNs or proxies?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aussieaddons/plugin.video.afl-video","title":"aussieaddons/plugin.video.afl-video","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aussieaddons/plugin.video.afl-video"}},"updates":{"snippets":[{"icon":"PERSON","message":"@andybotting in #2596: @gbvluva Were you doing anything with VPNs or proxies?"}],"action":{"name":"View Issue","url":"https://github.com/aussieaddons/plugin.video.afl-video/issues/2596#issuecomment-368702593"}}}

**Comment by andybotting** [comment]
These services tend to be pretty sensitive to using VPNs and proxies. We've this geoblocking happen across most of the streaming services we have add-ons for.

Let me know how you go with the next match, but I'll close your ticket for now.

cheers

**Comment by gbvluva** [comment]
Thanks, and really appreciate your work mate.
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 27/2/18, 11:46 am Andy Botting <notifications@github.com> wrote:
Closed #2596.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aussieaddons/plugin.video.afl-video","title":"aussieaddons/plugin.video.afl-video","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aussieaddons/plugin.video.afl-video"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #2596."}],"action":{"name":"View Issue","url":"https://github.com/aussieaddons/plugin.video.afl-video/issues/2596#event-1493325578"}}}

**Comment by allly17** [comment]
Hi I can’t login to afl video as it saying play.py(40)Aussie addon exception paid subscription not found for supplied username and password.please check the subscription type in settings is correct 
I have uninstalled the addon and repository and installed it again and password and username was still there not sure what to do

**Comment by gbvluva** [comment]
Sorry to bother you again but having issues again tonight with AFL Video. Pausing at login screen now and just won't start up. Like @ally tried re-installing through AU Addon repo on a different Pi and it's kept my login details. Is it maybe the repo? It did take unusually long to install.
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 27/2/18, 11:46 am Andy Botting <notifications@github.com> wrote:
Closed #2596.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aussieaddons/plugin.video.afl-video","title":"aussieaddons/plugin.video.afl-video","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aussieaddons/plugin.video.afl-video"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #2596."}],"action":{"name":"View Issue","url":"https://github.com/aussieaddons/plugin.video.afl-video/issues/2596#event-1493325578"}}}

**Comment by glennguy** [comment]
@ally17 just to check - you've paid for a subscription via the afl.com.au website? Or have you bought a subscription using Google Play/Appstore?

@gbvluva is your VPN still running tonight? Also, give it a few minutes at the login screen. I've seen it first hand take 180+ seconds for a response at some stages of the login process. Telstra's servers are probably getting hammered for these first few games while everyone is signing up for their free live pass on their mobiles.

**Comment by gbvluva** [comment]
I've just tried it and it worked with no VPN running, then again with a different VPN and it worked also, so as far as I can tell that one VPN address has been blocked. Will I have any issues using it without a VPN with a paid subscription (Telstra login)?

-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 27/2/18, 10:33 pm Glenn Guy <notifications@github.com> wrote:
@ally17 just to check - you've paid for a subscription via the afl.com.au website? Or have you bought a subscription using Google Play/Appstore?
@gbvluva is your VPN still running tonight? Also, give it a few minutes at the login screen. I've seen it first hand take 180+ seconds for a response at some stages of the login process. Telstra's servers are probably getting hammered for these first few games while everyone is signing up for their free live pass on their mobiles.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aussieaddons/plugin.video.afl-video","title":"aussieaddons/plugin.video.afl-video","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aussieaddons/plugin.video.afl-video"}},"updates":{"snippets":[{"icon":"PERSON","message":"@glennguy in #2596: @ally17 just to check - you've paid for a subscription via the afl.com.au website? Or have you bought a subscription using Google Play/Appstore?\r\n\r\n@gbvluva is your VPN still running tonight? Also, give it a few minutes at the login screen. I've seen it first hand take 180+ seconds for a response at some stages of the login process. Telstra's servers are probably getting hammered for these first few games while everyone is signing up for their free live pass on their mobiles."}],"action":{"name":"View Issue","url":"https://github.com/aussieaddons/plugin.video.afl-video/issues/2596#issuecomment-368844982"}}}

**Comment by glennguy** [comment]
Not sure - haven't tested yet this year with the AFL.com.au paid subscription. When I get time I'll sign up for the trial and give it a whirl.

**Comment by allly17** [comment]
Not sure why what’s the difference

**Comment by glennguy** [comment]
@allly17 The difference is in how we login/get authorisation from afl/telstra.

Did you purchase your subscription while in your mobile app, or did you buy it from this page: https://id.afl.com.au/livepass

**Comment by allly17** [comment]
From the page

**Comment by glennguy** [comment]
@allly17 If you signed up on the page, please go here: https://signon.telstra.com/login?goto=https%3A%2F%2Fsignon.telstra.com%2Ffederation%2Fsaml2%3FSPID%3DFanHub_AFL%26furl%3Dhttps%253A%252F%252Fsubscription.afl.com.au%252Faccount%252Flogin%26curl%3Dhttps%253A%252F%252Fsubscription.afl.com.au%252F&gotoNoTok=

and login with your username and password. Let me know how you go.
