### ISSUE TITLE
"NewConnectionError" - unable to play live video

### ISSUE THREAD

**Issue by dashingbenjamin** [aussieaddons/plugin.video.afl-video#2599]
Hi team,
I'm currently unable to play live video via the Kodi app on Mac, using mis-uuid login method (I've confirmed the uuid).

I've attached screen shots of the error for your interpretation.

Ps. No VPN's or other network trickery in play at the moment.
![screen shot 2018-03-22 at 6 42 31 pm](https://user-images.githubusercontent.com/37652583/37757438-2abea080-2e01-11e8-9374-57cbce558a1a.png)
![screen shot 2018-03-22 at 6 42 43 pm](https://user-images.githubusercontent.com/37652583/37757439-2af39a10-2e01-11e8-8213-a116ea3f8198.png)
![screen shot 2018-03-22 at 6 42 52 pm](https://user-images.githubusercontent.com/37652583/37757440-2b29cdc4-2e01-11e8-9bc8-9d7d00e55db3.png)

**Comment by dashingbenjamin** [comment]
Seems to have been intermittent.

**Comment by andybotting** [comment]
Thanks for the ticket anyway - it often helps others.

cheers
