### ISSUE TITLE
Loading error help.

### ISSUE THREAD

**Issue by CherlieBurgers** [aussieaddons/plugin.video.afl-video#2602]
Hi, I've ran the installation and keep getting an once all installed im getting an error in kodi:

AFL Video error: Check the log for more information.

I had a previous version working.
I can see on slack youve been contacted by 7, does this mean the AFL apps not wokring or could it be an install error by yours truly? 

im seeing Error getting plugin://plugin.video.afl-video/ then a couple errors after,

Log attached.  Thanks for your help!!!

![screen shot 2018-04-21 at 3 10 40 pm](https://user-images.githubusercontent.com/38578409/39080731-07c2d7b6-4578-11e8-8376-78e91e797a74.png)

**Comment by andybotting** [comment]
You're missing the aussieaddons common add-on, which is a dependency. It's failing to load because it can't be found.
