### ISSUE TITLE
Videos not Scraping Espcially News

### ISSUE THREAD

**Issue by sween64** [aussieaddons/plugin.video.afl-video#2604]
New videos aren't appearing within the add-on under their respective categories. There's only 1 video from the last two weeks under the news category.

**Comment by glennguy** [comment]
@sween64 I've just had a look in the Android app and it appears to be the same there - one video from the 29th, the rest are dated the 15th and earlier. Looks like something has gone wrong on Telstra's end, not much we can do about that sorry!

**Comment by sween64** [comment]
There are videos under the ALL section in the app that don't appear on the Kodi Add-On. Can we have an ALL section?

**Comment by glennguy** [comment]
@sween64 have addressed this in 160345f
