### ISSUE TITLE
Telstra free pass not authenticating

### ISSUE THREAD

**Issue by nazofm** [aussieaddons/plugin.video.afl-video#2607]
![image](https://user-images.githubusercontent.com/29671786/52189932-c4e09e00-288f-11e9-8720-bb485a387925.png)

its works on my iphone app and says its linked to my telstra ID but not finding an eligible service on my account. can you please take a look if something needs to be tweaked?

**Comment by glennguy** [comment]
Hi @nazofm 

Can you visit the url in your screenshot, login with your ID and see what it says? Don't do it on mobile data if you're doing it from your phone, connect to wifi first.

Your iphone app is working as Telstra knows who you are from connecting over mobile data - no need to enter Telstra ID.

I've just tried it out on my desktop and shows the mobile services that I have linked to my ID, and Kodi add-on is authenticating fine on my end.

**Comment by nazofm** [comment]
![image](https://user-images.githubusercontent.com/29671786/52193844-3e36bb80-28a5-11e9-9e29-396b259e00aa.png)

This is incorrect though as i obviously do have accounts linked. i tried the other option in settings for mis-uuid from my iphone app and that worked. i also got a couple of other mates to try the telstra login method and they all have the same result saying no accounts linked. something odd going on

**Comment by glennguy** [comment]
Impossible to know, we can only guess at how things work on Telstra's end.

As far as I know though setting up a Telstra ID is completely separate from signing up to a prepaid or postpaid service - it's up to the user. I have a couple of Telstra IDs that are linked to the same services, both had to be set up by me manually. Try following the steps in your image and you should have success.

**Comment by nazofm** [comment]
hmmm i have used your kodi app for years using the free telstra login method and it has always worked. now it says no services linked... strangely enough, I received an email today saying your AFL pass is now linked to your Telstra ID. see the image. Now when I login to my Ipad with my Telstra ID, I get my active AFL live pass too over Wifi. they must be using another method to authenticate a mobile account that has AFL pass then linking it to your Telstra ID. perhaps you could unpack the android apk for AFL and see what they have changed. just a thought.
![image](https://user-images.githubusercontent.com/29671786/52198929-9e832880-28b8-11e9-9a8e-8d26a07c35d7.png)

**Comment by nazofm** [comment]
never mind @glennguy it was my account. got telstra to refresh my account login and now all working fine. LOL sorry guys! love the app and the hard work.

**Comment by glennguy** [comment]
All good!
FWIW I've just tried linking live pass within the app and now it works if I select the paid subscription type. So we might need to update how that is labelled in the settings.

Happy viewing!
