### ISSUE TITLE
issue on android box

### ISSUE THREAD

**Issue by nazofm** [aussieaddons/plugin.video.afl-video#2608]
22:34:44.813 T:24927  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:34:44.814 T:24927  NOTICE: [AFL Video v1.8.8] Loading with params: {}
22:34:47.516 T:24936  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:34:47.516 T:24936  NOTICE: [AFL Video v1.8.8] Loading with params: {'category': 'Live Matches'}
22:34:47.517 T:24936  NOTICE: [AFL Video v1.8.8] Making video list...
22:34:47.518 T:24936  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:34:48.511 T:24936  NOTICE: [AFL Video v1.8.8] Performing GET for http://api.afl.com.au/cfs/afl/liveMedia?org=AFL&view=full
22:34:48.698 T:24936  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:34:49.380 T:24936  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/afl/seasons
22:34:50.442 T:24936  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:34:50.939 T:24936  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/afl/fixturesAndResults/season/CD_S2019014/round/CD_R201901401
22:34:51.706 T:24936  NOTICE: [AFL Video v1.8.8] Performing GET for https://app-league-aflw.yinzcam.com/V1/Game/Scores/?carrier=&height=1776&ycurl_version=1&os=Android&platform=Android&ff=mobile&mnc=0&app_version=1.0.5&version=5.7&width=1080&os_version=7.1.2&mcc=0&application=AFLW_LEAGUE&compId=CD_S2018264
22:34:52.718 T:24935   ERROR: CPythonInvoker(29, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.afl-video/default.py): script didn't stop in 5 seconds - let's kill it
22:34:52.718 T:24935   ERROR: GetDirectory - Error getting plugin://plugin.video.afl-video/?category=Live%20Matches
22:34:52.736 T:24703   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.afl-video/?category=Live%20Matches) failed
22:34:55.440 T:24954  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:34:55.440 T:24954  NOTICE: [AFL Video v1.8.8] Loading with params: {'category': 'All Match Replays'}
22:34:55.442 T:24954  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:34:55.671 T:24954  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/afl/seasons
22:34:59.178 T:24962  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:34:59.178 T:24962  NOTICE: [AFL Video v1.8.8] Loading with params: {'season': 'CD_S2018014', 'name': 'AFL Premiership 2018', 'current_round': 'CD_R201801427'}
22:34:59.179 T:24962  NOTICE: [AFL Video v1.8.8] Making rounds list...
22:34:59.180 T:24962  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:34:59.880 T:24962  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/afl/seasons
22:35:03.716 T:24971  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:35:03.716 T:24971  NOTICE: [AFL Video v1.8.8] Loading with params: {'round_id': 'CD_R201801427', 'season_id': 'CD_S2018014', 'name': 'Grand Final'}
22:35:03.716 T:24971  NOTICE: [AFL Video v1.8.8] Making video list...
22:35:03.718 T:24971  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:35:04.133 T:24971  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/afl/videos/round/CD_R201801427?pageSize=50&pageNum=1&categories=Match%20Replays&includeOnlineVideos=false
22:35:05.417 T:24971 WARNING: Attempt to use invalid handle 5
22:35:08.887 T:24990  NOTICE: [AFL Video v1.8.8] Kodi 18.0 running on Android
22:35:08.888 T:24990  NOTICE: [AFL Video v1.8.8] Loading with params: {'description': 'Watch the replay of the first quarter', 'title': 'GF: Eagles v Magpies Q1', 'subscription_required': 'True', 'genre': 'Sport', 'date': '2018-09-29 00:00:00', 'ooyalaid': 'R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt', 'thumbnail': 'http://s.afl.com.au/staticfile/AFL Tenant/Media/Videos/Thumbnails/2018/Sep/974216_thumb_326x184.jpg'}
22:35:09.146 T:24990  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:35:10.145 T:24990  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.sub.afl.com.au/cfs-premium/users?paymentMethod=ONE_PLACE
22:35:10.842 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for http://hub.telstra.com.au/sp2017-afl-app?tpUID=mis-uuid-8b245f70a501df8cfdc2dbcd2dc9dd5b&type=SportPassConfirmation&offerId=a482eaad-9213-419c-ace2-65b7cae73317
22:35:11.697 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for https://tapi.telstra.com/v1/sso/auth
22:35:13.027 T:24990  NOTICE: [AFL Video v1.8.8] Performing POST for https://signon.telstra.com.au/login
22:35:13.739 T:24990  NOTICE: [AFL Video v1.8.8] Sign-on result: {'raaGotoChain': 'signon.telstra.com/login|signon.bigpond.com/login', 'goto': 'https://tapi.telstra.com/v1/sso/idpcallback?cbs=eyJhbGciOiJIUzI1NiIsImtpZCI6bnVsbH0.eyJhdWQiOiJyYWEiLCJleHAiOjE1NDk0NTI5MTMyMDUsImlhdCI6MTU0OTM2NjUxMzIwNSwiY2FsbGJhY2tfc3RhdGUiOiI0Yzk5NTM2YS1mNTMxLTQ2MTAtOGI1ZS0wOTc2MTgyMGI1N2YifQ.kQmMGQORnaJt86eM2By9ZyQLNReoZqlVuyMuCP_JMEg&app_name=One Place Portal', 'cdcValBPSESSION': 'AQIC5wM2LY4Sfcy3B6eS5NB6cfFIveGFRpu+FL2RENcOiE8=@AAJTSQACOTkAAlNLAAk5MTM0NjM1ODIAAlMxAAIyMQ==#', 'raaURLAction': 'cdcTransfer', 'cookieName': 'BPSESSION|BPSESSION', 'cookieAction': 'write|write'}
22:35:13.739 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for https://signon.telstra.com/login?raaURLAction=cdcTransfer&raaGotoChain=signon.telstra.com%2Flogin%7Csignon.bigpond.com%2Flogin&cookieAction=write%7Cwrite&cookieName=BPSESSION%7CBPSESSION&cdcValBPSESSION=AQIC5wM2LY4Sfcy3B6eS5NB6cfFIveGFRpu%2BFL2RENcOiE8%3D%40AAJTSQACOTkAAlNLAAk5MTM0NjM1ODIAAlMxAAIyMQ%3D%3D%23&goto=https%3A%2F%2Ftapi.telstra.com%2Fv1%2Fsso%2Fidpcallback%3Fcbs%3DeyJhbGciOiJIUzI1NiIsImtpZCI6bnVsbH0.eyJhdWQiOiJyYWEiLCJleHAiOjE1NDk0NTI5MTMyMDUsImlhdCI6MTU0OTM2NjUxMzIwNSwiY2FsbGJhY2tfc3RhdGUiOiI0Yzk5NTM2YS1mNTMxLTQ2MTAtOGI1ZS0wOTc2MTgyMGI1N2YifQ.kQmMGQORnaJt86eM2By9ZyQLNReoZqlVuyMuCP_JMEg%26app_name%3DOne+Place+Portal
22:35:15.187 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for https://tapi.telstra.com/v1/media-products/catalogues/media/offers
22:35:16.163 T:24990  NOTICE: [AFL Video v1.8.8] Performing POST for https://tapi.telstra.com/v1/media-commerce/orders
22:35:16.507 T:24990  NOTICE: [AFL Video v1.8.8] Order status complete
22:35:16.646 T:24990  NOTICE: [AFL Video v1.8.8] Using token: mis-uuid-8b245f70a501df8cfdc2dbcd2d******
22:35:16.647 T:24990  NOTICE: [AFL Video v1.8.8] Performing POST for http://api.afl.com.au/cfs/afl/WMCTok
22:35:16.853 T:24990  NOTICE: [AFL Video v1.8.8] Fetching embed token: https://api.afl.com.au/cfs/users/mis-uuid-8b245f70a501df8cfdc2dbcd2dc9dd5b/token?embedCode=R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt
22:35:16.853 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for https://api.afl.com.au/cfs/users/mis-uuid-8b245f70a501df8cfdc2dbcd2dc9dd5b/token?embedCode=R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt
22:35:18.136 T:24990  NOTICE: [AFL Video v1.8.8] Performing GET for http://player.ooyala.com/sas/player_api/v1/authorization/embed_code/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt?device=html5&domain=http://www.ooyala.com&supportedFormats=m3u8&embedToken=http%3A//player.ooyala.com/sas/embed_token/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt%3Fapi_key%3DZha2IxOrpV-sPLqnCop1Lz0fZ5Gi.Gq2TW%26expires%3D1549366528%26signature%3DIuw8wakpYfXdZF4uqZZ7f9Jet2gf5BWN4tD6p3KMlfg%26account_id%3Dmis-uuid-8b245f70a501df8cfdc2dbcd2dc9dd5b
22:35:19.354 T:24990  NOTICE: [AFL Video v1.8.8] Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.afl-video/resources/lib/play.py", line 46, in play
                                                v.live, login_token)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.afl-video/resources/lib/ooyalahelper.py", line 281, in get_m3u8_playlist
                                                secure_token_url = get_secure_token(auth_url, video_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.afl-video/resources/lib/ooyalahelper.py", line 175, in get_secure_token
                                                res = sess.get(secure_url)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 525, in get
                                                return self.request('GET', url, **kwargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.aussieaddonscommon/lib/aussieaddonscommon/session.py", line 60, in request
                                                raise AussieAddonsException('Error: {0}'.format(e))
                                            AussieAddonsException: Error: HTTPConnectionPool(host='player.ooyala.com', port=80): Max retries exceeded with url: /sas/player_api/v1/authorization/embed_code/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt?device=html5&domain=http://www.ooyala.com&supportedFormats=m3u8&embedToken=http%3A//player.ooyala.com/sas/embed_token/Zha2IxOrpV-sPLqnCop1Lz0fZ5Gi/R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt%3Fapi_key%3DZha2IxOrpV-sPLqnCop1Lz0fZ5Gi.Gq2TW%26expires%3D1549366528%26signature%3DIuw8wakpYfXdZF4uqZZ7f9Jet2gf5BWN4tD6p3KMlfg%26account_id%3Dmis-uuid-8b245f70a501df8cfdc2dbcd2dc9dd5b (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x2bfa28dda0>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
22:35:19.366 T:24990  NOTICE: [AFL Video v1.8.8] Fetching connection information...
22:35:30.624 T:24703  NOTICE: Samba is idle. Closing the remaining connections
22:35:38.866 T:24703   ERROR: Playlist Player: skipping unplayable item: 3, path [plugin://plugin.video.afl-video/?description=Watch+the+replay+of+the+first+quarter&title=GF%3A+Eagles+v+Magpies+Q1&subscription_required=True&date=2018-09-29+00%3A00%3A00&genre=Sport&ooyalaid=R4MXJiZzE6B9m0S2SwQvgn6o3EpvWVlt&thumbnail=http%3A%2F%2Fs.afl.com.au%2Fstaticfile%2FAFL+Tenant%2FMedia%2FVideos%2FThumbnails%2F2018%2FSep%2F974216_thumb_326x184.jpg]
22:40:42.005 T:24685 WARNING: CPeripheralBusAndroid: failed to update input device with ID -3 because it couldn't be found
22:40:42.658 T:24685 WARNING: CPeripheralBusAndroid: failed to remove input device with ID 49 because it couldn't be found

**Comment by glennguy** [comment]
Hi @nazofm 
Non-debug log snippet and 'android box' doesn't help that much.
Can you turn on debug logging, restart your box, recreate the problem then choose 'send error report' from the debugging tab in the afl addon settings? Then comment the issue number here and I'll have a look.
`No address associated with hostname` would point to a dns issue of sorts, which is outside of the addon.
