### ISSUE TITLE
ssd_wv.dll

### ISSUE THREAD

**Issue by yioryos467** [aussieaddons/plugin.video.afl-video#2615]
ssd_wv.dll is missing from cdm directory. AFL Live matches won't start without this file. Tried adding it manually but not sure if I have the correct file.

It installed widevinecdm.dll as it required the Inputstream adaptive addon.

Even though I have 18.1 installed, it comes up saying you need Kodi 18 to play live streams....

**Comment by glennguy** [comment]
It should already be there normally...
Did you install from the windows store by any chance? If so you'll need to uninstall and use the regular installer.

**Comment by yioryos467** [comment]
Hi Glenn,

What exactly do I need to reinstall? Are you able to please provide me with
a link.

Regards
George

**Comment by andybotting** [comment]
George, can you confirm if you installed from the Windows Store?

For a direct install, download Kodi from here https://kodi.tv/download/849

**Comment by glennguy** [comment]
@yioryos467 Kodi itseIf. Just follow the link @andybotting posted - and to be specific, *don't* download the windows store version, but rather the 32bit or 64bit link.

**Comment by yioryos467** [comment]
Hi Glenn,

I actually downloaded direct from the Kodi website, currently running Leia
18.1. I'm reinstalling from scratch, I'll let you know how it goes.

Regards
George

**Comment by yioryos467** [comment]
Hi Glenn,

These are the steps I took...

1.  I Uninstalled Kodi off my system.
2.  Downloaded Kodi Leia 18.1 directly from Kodi website (64bit)
3.  Installed Kodi
4.  Downloaded the aussie repo from http://r.aussieaddons.com/
5.  Installed repo and AFL Video
6.  Added my Telstra details
7.  I tried to run Live Now AFL.TV
8.  It came up requesting I download the inputstream adaptive addon, which
I did
9.  It came up saying that widevinecdm.dll was missing and if I wanted to
install it, I clicked OK.  (It created cdm directory under Kodi directory
and only added the widevinecdm.dll file.
10. Clicked on AFL.TV but nothing happens.... it spins and them stops... no
play.

It did not come up with anything else required,  not even asking me to
install the ssd.wv.dll file....  So what am I doing wrong, this a clean
install of Kodi with only the aussie repo and AFL Video installed.

Any help would be appreciated.

Regards
George

**Comment by glennguy** [comment]
A debug log to look at is the next step.

*Turn on debug logging (in settings/system/logging, or press ctrl+shift+d)
*Restart Kodi
*Recreate the issue - try to play afl.tv
*Submit user report from afl-video settings (under debugging tab)
*Write back here with the issue number that it gives you

**Comment by yioryos467** [comment]
Hi Glenn,

I forced closed Kodi and restarted it, it worked ok.  I started my old
build (copied the cdm directory from the new install to my old Kodi build,
also running Kodi 18.1 Leia) and hen I tried to run AFL,TV, I get MISSING
SSD_WV MODULE REQUIRED FOR DRM CONTENT.....  ssd_wv.dll not found in  cdm
directory.

At a loss, works without the ssd_wv.dll in the fresh install and not with
my old build. Where can I get this ssd_wv.dll file?

Regards
George

**Comment by glennguy** [comment]
ssd_wv.dll comes with inputstream.adaptive. It will be at %appdata%\Roaming\Kodi\addons\inputstream.adaptive

If your old build is 32bit and new is 64 bit or vice versa then it won't work. Inputstream.adaptive is downloaded from here: https://mirrors.kodi.tv/addons/leia/

If your old build is from the windows store then it will never work.

**Comment by yioryos467** [comment]
All good, thank you for all your help....

Will there be a NBL addon? Its the only one we're missing....

**Comment by glennguy** [comment]
Glad it's working.

Re NBL, neither of us have subs so it makes it hard to develop for.
