### ISSUE TITLE
Rabsberry Pi 18+

### ISSUE THREAD

**Issue by CaptainTriangle** [aussieaddons/plugin.video.afl-video#2617]
I'm having problem with the add-on saying it requires Kodi 18+, I have version 18.1 installed and could watch the preseason stuff no problems but now I can't watch anything live on the add-on. 

I've tried live streams and live TV on other addons with no issue,  can anyone help with this

**Comment by glennguy** [comment]
Sure thing. Do you have the development repository installed? If so check for updates, there was an issue resolved earlier today.

Go to my add-ons, install from repository, then highlight the repo and bring up context menu (right click/long press/press 'c') and select check for updates. There's a dependency that should update and fix the issue.

**Comment by Ado78** [comment]
Hi Glennguy, I was having an issue on my retropie where I would select the live match to watch and it would look like it was loading but after a few seconds it just wouldn't load. Replays worked fine, just not live matches. Now I've just tried installing from the development repository following your instructions, but now when I go to watch a live match I get an error;

'Missing Widevine SSD module'
libssd_wv.so not found in any expected location.
ssd_wv module is supplied with Windows/Mac/LibreELEC,
and can be installed from most package managers in Linux
eg. "sudo apt install kodi-inputstream-adaptive"

then after pressing ok it says;

AFL Video v1.9.2
Kodi 18+ is now required to view live streams.

Replays still work fine, I have Kodi 18.1 installed, have tried rebooting after re-installing a couple times. Everything works fine on my laptop not sure why it's not working on my retropie. Any suggestions would be much appreciated.

Thanks

**Comment by glennguy** [comment]
Hi @Ado78 
Try ssh into your raspberry pi and run "sudo apt install kodi-inputstream-adaptive" . Hopefully the package is exists and is relatively up to date. libssd_wv.so should come with it and get installed to the correct location.

**Comment by Ado78** [comment]
Ah should have mentioned I already tried that too

**Comment by glennguy** [comment]
What was the result of it? Did it install or did you get something like 'unable to locate package' ?

If it did install, can you run `sudo find / -iname 'libssd_wv.so'` and let me know where it is? 

Also, if you could get us a debug log that would be great:
* Turn on debug logging in Kodi
* Restart Kodi
* Recreate the issue - try to play a live game or AFL.TV
* Go into afl-video addon settings, debugging tab and select 'send error report'
* Write back with the issue number

Thanks

**Comment by Ado78** [comment]
It said;
Reading package lists… Done
Building dependency tree
Reading state information… Done
Kodi-inputstream-adaptive is already the newest version (2.3.15-1~stretch).
Etc
0 upgraded, 0 newly installed

After running sudo find / -iname 'libssd_wv.so' it said this;
/usr/lib/arm-linux-gnueabihf/kodi/addons/inputstream.adaptive/libssd_wv.so

Issue number is
4345

Thanks so much for helping look into this!

**Comment by glennguy** [comment]
Ok I think this is a permissions problem, probably caused by the suggestion to run apt with sudo.

Pretty much we need to change owner of `/usr/lib/arm-linux-gnueabihf/kodi/addons/inputstream.adaptive/` to the same as the user Kodi runs as.

Our helper module is checking if the file exists, but because it has no permission to access it it's returning false.

Try running `sudo chown -R pi /usr/lib/arm-linux-gnueabihf/kodi/addons/inputstream.adaptive/`

**Comment by Ado78** [comment]
Nothing happened when running that :/. Tried it twice

**Comment by glennguy** [comment]
Well there should be no output if there's no issue with the command. But you still get the error complaining there's no libssd_wv.so file?

**Comment by Ado78** [comment]
Yeah same error. Replays still work fine

**Comment by CaptainTriangle** [comment]
Sorry for a slow reply,  the set up wasn't at mine and I left before I received any responses, I updated it and it worked fine,  I tried that yesterday but I guess it was before the patch was released. 

Thanks for the help.
