### ISSUE TITLE
Error in Kodi 18 - getdirectory failed?

### ISSUE THREAD

**Issue by chrislinke** [aussieaddons/plugin.video.afl-video#2618]
Errors trying to get this working - have the AFL Live Pass through Telstra, tried logging in via credentials, and also mis-uuid. 
Throws an error CGUIWindow::GetDirectory(plug-in://plugin.video.afl-video/) failed.
Happy to provide log screenshots and other info where required.
iOS 12.1.2 jailbroken on Unc0ver  iPhone X

**Comment by glennguy** [comment]
Hi @chrislinke 

A debug logfile would definitely be helpful, however are you trying to run it on your iPhone? If so due to the DRM there's no way to get the live streams working, only replays.

**Comment by chrislinke** [comment]
iPhone and iPad, I assume DRM works the same regardless though? iPad kids the AFL Video plug-in (but not play live videos), whereas iPhone can’t open the add-on. How can I get you the logs?

**Comment by glennguy** [comment]
DRM works fine in the official apps for iOS but there is no way to get that to work within Kodi unfortunately.

It's able to work on Windows/Mac/Linux as Kodi can leverage the DRM module that get's bundled as a separate file for Google Chrome, and Android being a Google thing has it built into the OS. With iOS if you want google's DRM system (Widevine) in your app you have to pay $ and sign an NDA, so I can't see it ever happening for Kodi that way. And anyway the iOS apps look like they are using Apple Fairplay which is a separate DRM system that Kodi has no support for at all.

Sorry to give you the bad news about the live games.

Regarding the iPhone not opening the addon, it would be great to see a log from that.

How to do:

* Turn on debug logging in Kodi (settings/system/logging)
* Restart Kodi
* Recreate the issue - try to open the addon
* Go into addons / my addons / video addons / afl-video / settings, debugging tab and select 'send error report'
* Write back with the issue number

**Comment by decasurf** [comment]
Having an issue on rpi3 librelec kodi 18 -

I get the following message-

Libwidevinecdm.so not found in /storage/.kodi/cdm 
Do you want to download the missing widevinecdm module for your system?

I click yes then get 

Http 404 error

Any ideas?
