### ISSUE TITLE
Having an issue on rpi3 librelec kodi 18 

### ISSUE THREAD

**Issue by decasurf** [aussieaddons/plugin.video.afl-video#2619]
Having an issue on rpi3 librelec kodi 18 -

I get the following message-

Libwidevinecdm.so not found in /storage/.kodi/cdm
Do you want to download the missing widevinecdm module for your system?

I click yes then get

Http 404 error

Any ideas?

**Comment by glennguy** [comment]
Hey @decasurf 

Thanks for bringing this to our attention. 

The updated links are now in our development version of our drm helper module, which should make it to the main repo sometime soon but to get up and running now you can install the dev repo, zip file [here](http://r.aussieaddons.com/repo-devel.zip) or if you already have that installed then force Kodi to check the repos for updates - go to install from repository, highlight our repo and bring up the context menu ('C', right click or long press) and select check for updates

Alternatively, you can ssh into your rpi3 and run `wget https://k.mjh.nz/.decryptmodules/widevine/1.4.9.1088-linux-armv7.so -O /storage/.kodi/cdm/libwidevinecdm.so && chmod 755 /storage/.kod
i/cdm/libwidevinecdm.so`

**Comment by shaunhp** [comment]
Thanks for this guys.  I had to use a different link on my Chromebox, since it's x86-64 CPU.  So for anyone interested it was:

wget http://k.mjh.nz/.decryptmodules/widevine/1.4.9.1088-linux-x64.so -O /storage/.kodi/cdm/libwidevinecdm.so && chmod 755 /storage/.kodi/cdm/libwidevinecdm.so

**Comment by decasurf** [comment]
Thanks all was working fine with dev version. Today I got a new missing item when trying to play live.

Missing Widevine SSD module
libssd_wv.so was not found in any expected location. 
ssd_vw module is supplied with Windows/Mac/libreElec and can be installed from most package managers in Linux eg. “apt install kodi-inputstream-adaptive”

Failed to play stream. Please visit our website at ... for more information.

Is there something I can do?

**Comment by shaunhp** [comment]
I had that same problem on Kodi 17.  Upgrading to Kodi 18 (takes 5 minutes) fixed that for me.

**Comment by decasurf** [comment]
Thanks Shaun already running Kodi 18.1 Libre Elec 9.0.1

**Comment by shaunhp** [comment]
Did you SSH in and run that command? Ps. I think I’m on Kodi 18.2

**Comment by glennguy** [comment]
@decasurf the change that broke that for you has been reverted so try force updating the repo (or it should happen automatically after some time) and that should sort it.

**Comment by jaypet** [comment]
Similar issue for me, 4694. I'm on rpi3, osmc though and don't think I have a /storage/.kodi/cdm/libwidevinecdm.so path? 
Do I need to update another config?

**Comment by jaypet** [comment]
> Similar issue for me, 4694. I'm on rpi3, osmc though and don't think I have a /storage/.kodi/cdm/libwidevinecdm.so path, i've had a look and have /home/osmc/.kodi/cdm/widevine/ - does that matter?

_might_ have fixed it for OSMC - by sshing in and running: 
wget https://k.mjh.nz/.decryptmodules/widevine/1.4.9.1088-linux-armv7.so -O /home/osmc/.kodi/cdm/libwidevinecdm.so && chmod 755 /home/osmc/.kodi/cdm/libwidevinecdm.so

**Comment by glennguy** [comment]
New version of DRMHelper published to the main repo which should fix this problem. Please start a new issue for further help.
