### ISSUE TITLE
V1.9.2

### ISSUE THREAD

**Issue by 24Clayton** [aussieaddons/plugin.video.afl-video#2621]
Having some issues with v1.9.2 tonight (6th/4) Live stream and replies not playing error message tasks of "Max tries exceeded with url" Any ideas?

**Comment by glennguy** [comment]
Hey @24Clayton 

Not to do with us from what I can see. I have the same issue here with iinet, but if I use my mobile data there's no problem.

Can access player.ooyala.com from my mobile browser (on mobile data) fine - it redirects to www.ooyala.com

Trying to access through iinet:
```
C:\Users\Glenn>ping player.ooyala.com
Ping request could not find host player.ooyala.com. Please check the name and try again.
```

So it would seem at least for me a DNS problem with iinet. No adblockers/getflix etc. here.

**Comment by 24Clayton** [comment]
Cheers for the confirmation, Glenn. I'm not with iiNet, so maybe the issue is a lot bigger and to do with Telstra or NBN

**Comment by 24Clayton** [comment]
Just tried playing on Android phone and iPad through Official AFL app. No joy. Seems issue is Telstra. Cheers again

**Comment by glennguy** [comment]
Have you tried using mobile data through the official app? 

What I'm saying is that it's my ISP. No issues using Telstra internet here in the app or on Kodi

**Comment by 24Clayton** [comment]
Yeah, have tried mobile data, and still have same issue

**Comment by glennguy** [comment]
Must be ooyala.com's DNS records. Others having the same issue according to the Whirlpool Forum

**Comment by 24Clayton** [comment]
Okay, thanks for everything

**Comment by glennguy** [comment]
They seem to have resolved this, closing and thanks for reporting @24Clayton
