### ISSUE TITLE
Live games not playing

### ISSUE THREAD

**Issue by rcborg1985** [aussieaddons/plugin.video.afl-video#2622]
I can play replays with no issues, and I don't get any authentication error on live games. It shows a loading circle for a second and then does nothing. I also have the rugby app and this has no issues with live games. I am on Xbox One

**Comment by andybotting** [comment]
Please see:
http://aussieaddons.com/addons/afl/
and
http://aussieaddons.com/drm/

Basically, the Xbox cannot stream live games as AFL now DRM encrypt those streams.
