### ISSUE TITLE
Live stream not working - 4484

### ISSUE THREAD

**Issue by PrFrink** [aussieaddons/plugin.video.afl-video#2623]
Hi, I updated by box to libreelec with kodi 18, having issues like others with watching live stuff. other stuff is fine.

ran a log - 4484 (and 4483 ran twice).

When addon tries to add updated file it errors http404 

tried deleting as per" "Just remove /storage/.kodi/cdm/libwidevinecd.so (or rename it if you're worried), then restart Kodi "
but only found a long numbered folder, rebooting kodi crashed the system (folder corruption" had to reinstall build again.

**Comment by glennguy** [comment]
Same issue as #2619. Have a look at my comment there and let me know if you have any further issues

**Comment by PrFrink** [comment]
Glenn you legend.
the update/long press didnt work, but SSH'd with putty and got it working with the code... just in time for the Richmond game, thanks champ.

**Comment by PrFrink** [comment]
Perhaps related but im unsure - live games are fine but replays are now choppy beyond watchable. Audio seems ok, video is really bad. 
Just thought I'd mention it, happy to wait for next upgrade.

**Comment by glennguy** [comment]
@PrFrink Any choppiness is on Kodi's side of things - our addon is only responsible for getting the link to the stream.

The replays are a higher quality and higher bitrate than the live stream. Live is around 1.6Mbps and replays 2.4Mbps. If you've got a slow or congested connection, or using wifi then I'd think that would be the culprit. Case in point - was having the same issue on a relative's rpi3 with buffering and choppiness over wifi. The link speed was reported as 72Mbps but it was taking 10 seconds to buffer a 4 second chunk. Changing the wifi channel on the access point fixed it somewhat even though link speed/signal strength was largely reported as the same. There was still some intermittent issues with it though so the proper solution for this situation was a usb wifi module with external antenna ($~25). Ethernet is the real solution but he doesn't want to outlay for it. Hope any of that info helps!

**Comment by PrFrink** [comment]
Thanks for the response Glenn, my box is a little old now but it's been always connected via ethernet.
The replays have been playing fine previously, I have a new build on the box (went from ember to libreElec recently) to get kodi 18 so I can get the AFL  livestreams, so im very happy to get that working again. 
Replays are stuttery since this new build, I noticed some of my personal files (VOB) were stuttery too and  corrected by removing the interlace function. this improved the AFL replay a tad, but not fixed. 
Still, no biggy, if I find a tweak that works i'll post back, but live streams are the primary purpose of this addon which have been back to perfect, so cheers.
