### ISSUE TITLE
Live stream not working

### ISSUE THREAD

**Issue by richmond1212** [aussieaddons/plugin.video.afl-video#2624]
I have version 1.9.2 afl add on and valid telstra login

Replays work fine however when selecting a livestream it does nothing. It looks like it thinking to load, pauses for a second but then nothing.  No error code given.

**Comment by glennguy** [comment]
Hi @richmond1212

We need a bit more info from a debug log:

Turn on debug logging in Kodi (settings/system/logging)
Restart Kodi
Recreate the issue - try to open the addon
Go into addons / my addons / video addons / afl-video / settings, debugging tab and select 'send error report'
Write back with the issue number

**Comment by richmond1212** [comment]
Thanks, did those steps and issue number is 4500

**Comment by shiftrs** [comment]
Exact same issue here, 4537

**Comment by richmond1212** [comment]
I reinstalled kodi from the website and it works now? Weird. Maybe it was the 18.1 version as normally i doanload kodi from thr windows app store

**Comment by PrFrink** [comment]
Hope you got to watch the end 😀

**Comment by shiftrs** [comment]
I've tried a full re-install on my rpi3 but still having the same issue. Works perfectly fine on Windows

**Comment by fabio85t** [comment]
I have the same issue 4542

**Comment by glennguy** [comment]
Ok first up - @richmond1212 
You're correct - the windows store version doesn't support DRM which is now required for AFL.

@shiftrs 
`ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/pi/.kodi/cdm/libwidevinecdm.so)` wrong version or missing - our link for this file is currently broken (working on an update that's coming soon). See #2619 for a quick workaround.

@fabio85t  - I can't see that you've tried to play anything in the log. Can you attempt to play a live stream and then submit the error report?

**Comment by fabio85t** [comment]
Still not working. Issue 4552

**Comment by glennguy** [comment]
`ERROR: AddOnLog: InputStream Adaptive: Unable to initialize media_drm`

This says that your Android device can't handle DRM (widevine) encrypted streams. Can you install DRM info from the play store and see what widevine level your device says it is?

**Comment by fabio85t** [comment]
Level 22

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennguy** [comment]
That doesn't sound right. Security level should either be L1 or L3

**Comment by fabio85t** [comment]
[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennguy** [comment]
You'll need to attach the image in a browser, email replies don't work.

**Comment by fabio85t** [comment]
[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennguy** [comment]
@fabio85t
Regardless of the DRM info, fixing your issue isn't with the add-on itself. You can confirm this by trying Netflix on your device, same DRM system.

**Comment by shiftrs** [comment]
Hi @glennguy apologies for the delay in getting back to you.
I was indeed getting the 404 error initially which was fixed by using the wget from #2619 - however after using the workaround, the new issue arose which is exactly as described in OP - the video starts to load and then immediately quits with no error code. Do you need me to send through another debug log?

**Comment by fabio85t** [comment]
Na thats all good. Yeah if i can  thanks for that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by glennguy** [comment]
@shiftrs yeah a debug log would be great

**Comment by phobi4n** [comment]
Getting 404 error on stream. Widevine seems to work (e.g. Netflix plays). Attached is debug kodi.log hope it helps. Have a mate who's gettin' a bit stressed not being able to watch his footy ;)

[debug-kodi.log](https://github.com/aussieaddons/plugin.video.afl-video/files/3096806/debug-kodi.log)

**Comment by andybotting** [comment]
@phobi4n Your log file looks very different to mine. How about you send us a real log file by going into the add-on settings and clicking on debugging -> Send error report and letting us know the number it gives you

**Comment by phobi4n** [comment]
4608 - might have done that a few times tho.

**Comment by glennguy** [comment]
@phobi4n can't see anything in that log - debug logging is turned off and the issue hasn't been recreated.

However if you're getting 404s for the chunks then it's likely the same issue as in #2620. Your system clock is not accurate. Synchronise it and it should work.

**Comment by phobi4n** [comment]
Adjusted clock after last message for other reasons. Just got a reply from Rob, all is working. He asked me to pass on his thanks. I guess this closes the issue for me.

**Comment by BigTons** [comment]
@glennguy hoping you might be able to help. I appear to be having the same issue as @fabio85t regarding DRM (ran DRM Info and SDK level is 22 also). 

My log is https://github.com/aussieaddons/issue-reports/issues/4783

Does it come down to hardware? Ie no fix available for the android machine I have or can I install/update?

**Comment by glennguy** [comment]
@bigtons looks like it unfortunately: `ERROR: AddOnLog: InputStream Adaptive: Unable to initialize media_drm`

Comes down to your OS, it seems a lot of the Android 5.1 boxes aren't working with widevine DRM like this/Netflix etc.

**Comment by glennguy** [comment]
Locked this issue, please start a new one if you're having problems.
