### ISSUE TITLE
Afl won’t live stream. #5002

### ISSUE THREAD

**Issue by chuckau** [aussieaddons/plugin.video.afl-video#2626]
Can watch replays but not live games. I click on the game and the loading spins a couple of time but does nothing

**Comment by andybotting** [comment]
Have you sent us an issue report yet? Although it does sound a lot like you don't have your DRM decryption set up. What platform are you running on?

Please read http://aussieaddons.com/addons/afl/ and http://aussieaddons.com/drm/ for some tips and let us know if you're still having trouble.

**Comment by chuckau** [comment]
Thanks Andy, below are the issue details 

Https://GitHub.com/aussieaddons/issue-reports/issues/5051

**Comment by glennguy** [comment]
Hey @chuckau
```
2019-06-09 16:05:46.133 T:12887   ERROR: AddOnLog: InputStream Adaptive: Unable to initialize media_drm
2019-06-09 16:05:46.134 T:12887   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
```
This from your log indicates your Android setup is lacking widevine support, or reporting the widevine level incorrectly. It's outside of what our add-on does but maybe we can help point you in the right direction. Are you on original firmware/rom or custom? Often flashing a custom firmware can overwrite the devices DRM keys, or the custom rom says the device can do widevine L1 when it's only capable of L3.

**Comment by glennguy** [comment]
Also there's an app in the play store called DRM info that might shed some light. Under Widevine CDM you want to look for the security level.

**Comment by chuckau** [comment]
I found an app that has this information, but it doesn’t come up with any details. So I fussing it’s not supported. The firmware is out of the box. I haven’t touched it

**Comment by glennguy** [comment]
AFL is currently not using widevine, closing now
