### ISSUE TITLE
Can't Livestream on Sony Android TV

### ISSUE THREAD

**Issue by geoffhop** [aussieaddons/plugin.video.afl-video#2627]
Hi there
Previously been using v1.9.2 on a Sony Android TV without issue for months but can no longer live stream games replays are fine, typically it just refuses to play but will sometimes play audio only. Add-on is still working fine on my Vodafone TV device but no joy on the Sony. Suspect an update has messed with DRM but not sure how to diagnose.
Any ideas welcome.
Thanks in advance
Geoff

**Comment by glennguy** [comment]
Hi @geoffhop

Sorry about the late response.

It's possible that widevine needs reprovisioning again, which I thought
inputstream.adaptive was now meant to sort out but maybe it's not working
or you're running an older version.

You could try seeing if the Netflix Android app will play something (which
would definitely do the provisioning), if that plays then try again with
AFL.

**Comment by geoffhop** [comment]
Hi there
Netflix is and has been working without issue.
Funny thing is the add-on worked fine today for the Melb v Freo game but will now not live stream either the Port v Geel or Saints v Lions, just trys to start the stream and then fails.
Thanks again
Geoff

**Comment by glennguy** [comment]
Could you send us a debug log?
* Enable debug logging in Kodi settings -> system -> logging (don't enable component specific logging though)
* Restart Kodi
*Try to play the stream in AFL add-on
* Go into AFL add-on settings and choose 'send user report'
* Write back here with the issue number given

Thanks!

**Comment by geoffhop** [comment]
Hi there
Issue number is 5095
Thanks
Geoff

**Comment by glennguy** [comment]
Ok this one looks easy - the clock on your tv is wrong, looks like it is
running fast by roughly a minute (assuming you're on Perth time?)
Fix that and you should be good to go. Might need some trial and error if
it won't sync the time automatically.

**Comment by geoffhop** [comment]
Thank you,  I have changed date setting from broadcast time to network time and will attempt to try when live stream is on.
Is there a link to the log file I sent you? Would love to look at it to see the details.
Thanks again
Geoff

**Comment by glennguy** [comment]
Issue is here: https://github.com/aussieaddons/issue-reports/issues/5095

Click on 'full log' to see the Kodi log.

The 404 errors for the stream segments are caused by the incorrect clock time as the segment number is calculated from the clock time, and there's only ever a 60 second window of 6 second (I think) segments available at any one time.

We're looking at adding a check in the add-on for this to be able to tell the user if the clock is out.

**Comment by glennguy** [comment]
Should be no further issues with this for no as AFL is no longer using DASH/Widevine for live matches.
