### ISSUE TITLE
AFL VIDEO V1.9.2.3-g3e2e499 ERROR

### ISSUE THREAD

**Issue by fuddstar2012** [aussieaddons/plugin.video.afl-video#2629]
play.py (47)- AussieAddonsException: Stored token has expired, please try and play this item again. if this error persists please submit an issue on github.

**Comment by glennguy** [comment]
Hi @fuddstar2012

Have you tried using the option in the AFL add-on settings to remove the
stored login token?

**Comment by fuddstar2012** [comment]
I will try that Glenn . Will I need to sign back in ? Will let u know thanx so much

**Comment by fuddstar2012** [comment]
Hi Glenn I removed the token and tried again, however I am getting the same error.

 

I really don’t understand it as I have the FREE Telstra access and never had any trouble over many years now.

 

I don’t know if its related, but Indigo hasn’t worked for me for some time. I used to install the apps directly from there however I 

 

Get an error log report there as well. In saying that indigo doesn’t work on another box but AFL app works there. 

 

I am devastated and am grateful for your help

 

Regards 

 

Brendan

**Comment by glennguy** [comment]
I've never used indigo but from what I can tell at best it's bloatware that you don't need, at worst potentially malware/spyware. I would remove it if I were you. Our add-ons are only designed to work correctly using our repo, see http://aussieaddons.com/installation/ if AFL hasnt been installed from our repo.

Back to your issue - try using the mobile app to link your subscription to your Telstra ID then change the subscription type in the add-on to paid/linked. You'll need to then clear the stored token again before retrying.

**Comment by fuddstar2012** [comment]
Thank you Glenn 
The problem does come from problems with my subscription and the id need to take it up with Telstra .. but wanna keep it on the down low on how I am using the app.. many thanks Glenn 

You are a champ for trying help .. over the time I think I  have logged in too many devices . Gunna get that indigo off 

Cheers Glenn

**Comment by glennguy** [comment]
@fuddstar2012 I've just helped another user in issue #2630 with a similar problem if you wanted to have a look.

Never managed to get it solved but my feeling was that having non-mobile services such as home broadband linked to the same Telstra ID was at the root of it as in the past this has been an issue (Telstra have even specified that it won't work, and the only way to solve was to create a new Telstra ID and not link home broadband to it, only the eligible mobile service).

The easiest way forward would be to activate the live pass on the mobile app (over mobile data) and link the live pass to your Telstra ID - details in my post [here](https://github.com/aussieaddons/plugin.video.afl-video/issues/2630#issuecomment-512673456)

**Comment by fuddstar2012** [comment]
Glenn thank you so much, superstar cheers

 

 

Brendan

**Comment by fuddstar2012** [comment]
Hi Glenn 

 

I was trying to load the AFL app to get ready for the upcoming season and non of the zip files work ?

 

Do you please tell me where the latest zip file is ?

 

All the best 

 

Brendan

**Comment by andybotting** [comment]
@fuddstar2012 You'll need to install from our repository. If you try and install the zip file directly, it can't resolve the add-ons dependencies. 

See the Aussie add-ons install page https://aussieaddons.com/installation/

**Comment by fuddstar2012** [comment]
HII Andy 

 

I didn’t realise you were still involved with your app..

 

Thank you so much 

 

What is the mobile data option in the settings 

 

Cheers

 

brendan

**Comment by andybotting** [comment]
It's for authenticating with Telstra using mobile data rather than the username/password option. You can use this if you're planning on using the kodi with only 4G and not wifi I believe

**Comment by fuddstar2012** [comment]
Many thanks have a great year

**Comment by andybotting** [comment]
Thanks, you too!

**Comment by fuddstar2012** [comment]
Hi Andy 

 

May I ask if there are any live streams in 2021 for the AFL live app?

 

Kind Regards

 

Brendan

**Comment by andybotting** [comment]
@fuddstar2012 Nope. This explains why: https://crowdsupport.telstra.com.au/t5/news-feed/information-on-afl-and-nrl-live-passes-for-season-2021/ba-p/918279

**Comment by fuddstar2012** [comment]
Andy and Glenn 

 

Thank you so much for the joy and happiness to myself and other people who enjoyed your apps.

 

We owe you more than can be explained.  

Just want to let you know that it was REALLY REALLY appreciated. 

 

I don’t think it will ever be matched

 

Kindest Regards CHEERS 

 

Brendan

**Comment by andybotting** [comment]
Cheers Brendan.. we appreciate it!

**Comment by glennguy** [comment]
You're welcome Brendan, happy that we've made you happy!

We'll still support all the other content it provides, as well as live AFLW games. Sad though about the main AFL games...

**Comment by fuddstar2012** [comment]
Glenn and Andy  you guys did so much and it still great to have access to the replays . Its only when its gone people can truly appreciate what was on offer. True Kodi legends
