### ISSUE TITLE
Aussieaddon AFL app FL live Channel

### ISSUE THREAD

**Issue by fuddstar2012** [aussieaddons/plugin.video.afl-video#2636]
AFL app is playing Fox AFLW 503 channel with heading of 504 which is mens Afl. the system has been tricked playing the Fox Channel 503 with the heading of fox live 504 Channel which is the WRONG GAME..happened last night too. Will this change into the future ? HELP Glenn.
regards Brendan

**Comment by geoffhop** [comment]
Hi fuddstar2012
Out of interest are your live matches dropping out of the Live Matches section once the game starts? I am on 1.9.4 on Android and mine go missing so I can never watch a live game!
Thanks in advance
Geoff

**Comment by fuddstar2012** [comment]
Yes Geoff, it could be a menu structure thing, it was the same last night. I notice on the phone the match plays.

**Comment by glennguy** [comment]
Fixed in v2.0.0, thanks everyone for reporting! 👍
