### ISSUE TITLE
AFL Live Games go missing

### ISSUE THREAD

**Issue by geoffhop** [aussieaddons/plugin.video.afl-video#2637]
Hi there
Using V1.9.4
In the lead up to a live AFL game the games are listed in the Live Matches section but once the game starts it goes missing from the list leaving you unable to watch a live game.
Thanks in advance
Geoff

**Comment by pinheadmercs** [comment]
Me too, last nite it happened for the Saints game... I reinstalled everything, but it disappears at the start of the game, ended up logging into my AFL app on my phone :)

**Comment by fuddstar2012** [comment]
Thats right geoff, Pinhead, usually there is a list of the live games written in green, however there was no list, it just went str8 to AFLW

**Comment by fuddstar2012** [comment]
Last night was the same..

**Comment by geoffhop** [comment]
Yeah same with mine, I have and older version 1.9.2 on a tablet and it is acting the same, first noticed it for the Saints game last night, also could not get the blues v pies aflw to live play last weekend either

Sent from Yahoo7 Mail on Android 
 
  On Fri., 21 Feb. 2020 at 18:16, fuddstar2012<notifications@github.com> wrote:   
Thats right geoff, Pinhead, usually there is a list of the live games written in green, however there was no list, it just went str8 to AFLW

**Comment by fuddstar2012** [comment]
I am running 1.9.4 aussieaddons. The menu definitely looks different

**Comment by geoffhop** [comment]
With a bit of luck Glen is seeing these and we will get a fix, such a great add-on he's built.

**Comment by fuddstar2012** [comment]
Glenn and Andy has helped me in the past. Gurus. I would say over time the quality has got better and better

**Comment by glennguy** [comment]
Ok I'm here, having a look now :)

**Comment by fuddstar2012** [comment]
Thank you Glenn

**Comment by geoffhop** [comment]
Cheers Glenn

**Comment by glennguy** [comment]
My app is out of date, just getting the lastest version set up. 

The issue will be that although the data for afl.tv is still in the same place, live matches this year are probably found somewhere else.  Just need to find where and update the addon accordingly. Hopefully there's nothing trick about it.

**Comment by fuddstar2012** [comment]
Cheers,

The AFLW and the AFL both have the FOX 504HD LIVE logo however the AFLW was officially on FOX 503 I think..

**Comment by fuddstar2012** [comment]
Hi Glenn
I think I may have found it, when you left click in the menu listings ie view type go down to actions " Go to playlist click that and 504 FOOTY PLAY comes up, click that and it mirrors whats on Fox at the moment. Whereas LIVE Now AFL.TV has a replay on..

**Comment by fuddstar2012** [comment]
Sorry Glenn , 504 Footy Play is no longer there it has AFL TV there now..for a second i thgt id cracked the 
Davinci Code..

**Comment by glennguy** [comment]
Don't worry about 503/504 etc, AFL.TV is just a streaming 'channel'. It's the same as you can get on a telstra box. It's all replays, taken from wherever.

Anyway I've got playback, just need to tidy some stuff up and I'll release tomorrow, gtg to bed! :)

**Comment by fuddstar2012** [comment]
Thank you Glenn,

 

Thanks doesn’t seem enough, Being able to watch and use this app brings us so much pleasure.

 

Brendan

**Comment by glennguy** [comment]
Fixed in v2.0.0, thanks everyone for reporting! 👍

**Comment by geoffhop** [comment]
Thanks Glenn, great stuff, very much appreciated, will give it a whirl later today

**Comment by fuddstar2012** [comment]
Hi Glenn I am getting the Missing inputstream.adaptive error anyone else please

**Comment by fuddstar2012** [comment]
Hi Geoff are you getting any errors ?

**Comment by glennguy** [comment]
Install inputstream adaptive from the main Kodi repository. It should be under videoplayer inputstream category

**Comment by geoffhop** [comment]
Hi there
Initially my devices upgraded to 2.0.1 and would not work, so I uninstalled both the add-on and the source and upgraded to 2.0.2 and got it running on 4 seperate devices 3 Android and 1 librelec on a raspberry pi got blues v dogs in aflw and now fees v crows, a bit slow to load but is working

**Comment by fuddstar2012** [comment]
Yes done that, now Foxtel go isn’t working must have a dependency conflict or ?

 

Cheers

Brendan

**Comment by fuddstar2012** [comment]
Thanks Geoff,  this adaptive input stream is a bugger of a thing happened a few years ago, I think then it was some conflict dependancy

**Comment by glennguy** [comment]
Shouldn't be a dependency conflict, you probably would have needed it for foxtel go anyway I would have thought.

Is this addon working for you now?
