### ISSUE TITLE
Cannot update to V2.0.2 on my device

### ISSUE THREAD

**Issue by 3HEADFROMAUSTRALIA** [aussieaddons/plugin.video.afl-video#2638]
Was quietly lurking in the other thread waiting for an update to watch the Marsh series and went to update the addon but is unable. The device is a Xiaomi Mi Box 4.

I have 2 other devices (PC & TV /android tv) that can update to it, just not the MiBox4. Is it a limitation of the device?

 Cheers for updating so I can watch on the other devices at least though!

**Comment by 3HEADFROMAUSTRALIA** [comment]
reinstalled kodi and aussieaddons repo - and now working - apologies, not sure why it wasn't updating by itself.

Thanks again for the addon, love it!

**Comment by geoffhop** [comment]
Yeah I found the same, needed to uninstall to upgrade, now all good

**Comment by pinheadmercs** [comment]
thanks for everything

**Comment by glennguy** [comment]
Glad you got it fixed!

Another way to go without having to uninstall/reinstall the repo is to force the repo to check for updates

If you're using the default Estuary skin:
Go to addons
Up the top click on the 'open box' icon
go to 'install from repository'
highlight our repo
bring up the context menu (right click, long press, or press 'c')
select 'check for updates'

Kodi automatically does this but only around every 6 hours.
