### ISSUE TITLE
AFL streams not starting reliably 2.0.2

### ISSUE THREAD

**Issue by berlinchair** [aussieaddons/plugin.video.afl-video#2639]
Updated to the latest version today - having trouble with the AFL stream not working on CoreElec 9.2.1 on Odroid N2.  
The AFLW live streams have started OK, the AFL.TV one didn’t want to start just now either. I did get some coverage of the Adel v Melb game earlier on but can’t get GC v Geel for love or money!! There was a lot of buffering too which is pretty unusual for my connection. 
Any ideas on anything I might be able to tweak, or is there a log I can provide you with to try to debug?
Thanks for your work on this add on, my footy mad son and I love it during the season!!

**Comment by glennguy** [comment]
hey @berlinchair 
Make sure you're on version 2.0.2 and try a restart of Kodi once updated.

It's working fine here but does take about 20 seconds to actually start playback. This can be mitigated in Kodi 19 with inputstream.adaptive, I'll see if I can get the changes backported for Kodi 18/inputstream.adaptive

It can timeout before playback begins, generally once it hits around 30 seconds. On the technical side Kodi is downloading the first segment from each of the 10 bitrate levels provided to check what's the best bandwidth stream to use for your connection.

Let me know how you get on!

**Comment by berlinchair** [comment]
Funnily enough not long after I posted that it decided to work - it was after a reboot although having said that I’ve rebooted a couple of times earlier which made no difference!!
Then I started looking at the settings and tried to select a different stream via ‘select program’ which gave me sound but no video. So tried to reload from start again and wouldn’t play ball again :-/
Any way to tell it to only go for one stream and just load that one? Might be quicker and avoid timeouts perhaps?
Thanks for your help and time :-)

**Comment by glennguy** [comment]
What kind of connection speed do you have at this time of the night?

We used to be able to let you select the stream, but now the audio and video come from separate locations and there's no way to manually give both to Kodi...
I know in the current situation there's going to be a lot of headaches so I'll investigate another way around. We might be able to run a local proxy server that will take the master manifest file and rewrites it with only the bitrates we want. But don't hold your breath. 

It's a better solution to try and get inputstream adaptive working with this type of stream in Kodi 18. I've already had the changes necessary added to the Kodi 19 version of inputstream.adaptive so I'll backport them to Kodi 18 and request them to be added before the next i.a release.

Now that you mention your connection speed, try taking wifi out of the mix if you can.

**Comment by berlinchair** [comment]
Generally pretty good, but the fact that a video coming from my NAS was buffering tells me something is not happy with the local network.
connected via wired ethernet, but have rearranged the cables to try to take one of the switches out of the equation........ will report back if that makes any difference.

**Comment by berlinchair** [comment]
Well, there ya go. Connected more directly to the router and now loads up with no issues and minimal buffering. Maybe my old cheapy Netgear gigabit switch is not up to the job!!
Thanks a lot for your help, and thanks again for your great work

**Comment by glennguy** [comment]
That's great news!

Happy to help :)
