### ISSUE TITLE
Live Matches not playing 

### ISSUE THREAD

**Issue by hawksta** [aussieaddons/plugin.video.afl-video#2640]
I cannot get live matches or afl.tv  to play...I am on version 2.0.3

**Comment by hawksta** [comment]
Also I do not have a DRM helper addon...i seem to recall last year at beginning of season having the same issue

**Comment by hawksta** [comment]
Just had a look at closed issue 2639 and my problem is the same.  AFLW live matches will play,  but not afl.tv or the main afl live matches.  I've rebooted kodi a few times but still no luck...i am connected by ethernet  cable and running a vpn as I'm overseas...

**Comment by glennguy** [comment]
Hey @hawksta 

How is the issue presenting? Are you getting a message about drm helper?

Did you install the addon from our repository i.e in Kodi using the 'install from repository' option? Or install from zip?

**Comment by glennguy** [comment]
So is it just sitting there with the spinning circle for half a minute or so and then failing?

**Comment by hawksta** [comment]
Correct

**Comment by hawksta** [comment]
It is not asking for a drm helper

**Comment by glennguy** [comment]
Ok give me a few minutes, a new version of inputstream.adaptive has been pushed with the required changes to be able to play these live streams.

What you're experiencing is just Kodi giving up from waiting too long, unfortunately with our 3rd world internet it doesn't help. I'm on 50mbps and it still takes 20 seconds to get going, not far from the 30 second timeout.

**Comment by hawksta** [comment]
Ok.... thanks heaps.... I'll wait to hear from you

**Comment by glennguy** [comment]
I've pushed it to the dev repo. If you have the development repo installed then force Kodi to check it for updates. To do this:

In the default (estuary) skin:

Go into Add-ons -> go into the 'open box' icon -> install from repository -> highlight our repo and bring up the context menu (long press, 'c', or right click) and select 'Check for updates'

If you don't have the dev repo installed, the zip for the the changes just made is [here](https://github.com/aussieaddons/repo-devel/raw/master/plugin.video.afl-video/plugin.video.afl-video-2.0.3-1%7Eg1d7237b.zip)

**Comment by glennguy** [comment]
Actually just wait 2 minutes before checking the repo - github cache is slow to update

**Comment by glennguy** [comment]
It's there now...

**Comment by hawksta** [comment]
Is it still Version 2.0.3

**Comment by glennguy** [comment]
2.0.3-1~g1d7237b
Is your repo 'Aussie Add-ons', or 'Aussie Add-ons (development)' ?

If you want the development repo the zip is [here](http://r.aussieaddons.com/repo-devel.zip)

Otherwise you can download the afl zip from my post above

**Comment by hawksta** [comment]
So if i want to reinstall the repo what address am i using...i tried the main one and there is no zip file there

**Comment by hawksta** [comment]
http://aussieaddons.com/afl/

**Comment by hawksta** [comment]
Sorry that's wrong

**Comment by glennguy** [comment]
There's hyperlinks in both posts above (in blue)

Dev repo is http://r.aussieaddons.com/repo-devel.zip
Afl addon is https://github.com/aussieaddons/repo-devel/raw/master/plugin.video.afl-video/plugin.video.afl-video-2.0.3-1%7Eg1d7237b.zip

**Comment by hawksta** [comment]
http://aussieaddons.com/addons/afl

**Comment by hawksta** [comment]
So I'm talking to you via my phone and trying to update my android box.... is the devo repo the one i should download on my android box (add source)

**Comment by glennguy** [comment]
If you're going the add source way, comprehensive instructions are at http://aussieaddons.com/installation/

in short add the source as http://r.aussieaddons.com and install repo-devel.zip from there. You can then update the addon

**Comment by hawksta** [comment]
Still the same issue.... updated the addon.... restarted kodi and my whole box actually.... still timing  out

**Comment by glennguy** [comment]
Are you in Kodi 18?

**Comment by hawksta** [comment]
18.5

**Comment by glennguy** [comment]
Go into add-ons , then the open box icon, then install from repository, then Kodi add-on repository, then video player inputstream, and install inputstream adaptive. If it's already installed, enable it

**Comment by hawksta** [comment]
Nope..... it was installed and enabled already.... still no luck getting them to play

**Comment by glennguy** [comment]
Let's go to the next step - debug log

Here are the steps:
* enable debug logging in Kodi - go to Kodi settings, System, Logging and toggle 'Enable debug logging'. Don't turn on the component specific logging though.
* restart Kodi
* Open the afl addon, try to play a live match.
* After the video timeouts, go into the afl addon settings, go to the debugging tab, and select 'Send error report'

It should give you an issue number but I'll probably see it anyway. I'll have a look and hopefully the issue will present itself there! :)

**Comment by hawksta** [comment]
5773

**Comment by glennguy** [comment]
Ok I think I've worked it out. I can't update inputstream adaptive on Kodi Android, it must be packaged with it.
So we need to upgrade to Kodi 18.6 to get the correct inputstream adaptive version.
It's not available just yet on the playstore (should be in the next few days) but you can always sideload it (I can't provide instructions for this but Google is your friend)
Here are the links to the apks:
http://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.6-Leia-arm64-v8a.apk for 64 bit Android processor
http://mirrors.kodi.tv/releases/android/arm/kodi-18.6-Leia-armeabi-v7a.apk for 32 bit
Try the 64 bit one first.

If it's easier, open the browser on your Android box and go to kodi.tv and follow your nose to get the download page up for Android

**Comment by hawksta** [comment]
Ok... let me try

**Comment by hawksta** [comment]
Champion..... works like a charm now... thanks heaps

**Comment by glennguy** [comment]
Happy to help, thanks for hanging in there!

**Comment by hawksta** [comment]
To easy.... we got there... thanks again

**Comment by hawksta** [comment]
Side question.... does the cricket addon show all matched around the world

**Comment by glennguy** [comment]
No, typically it's got some Sheffield Shield matches but nothing 'premium'.

**Comment by hawksta** [comment]
Ok.... thanks again

**Comment by glennguy** [comment]
No probs :)
