### ISSUE TITLE
Richmond Carlton Game Missing

### ISSUE THREAD

**Issue by hawksta** [aussieaddons/plugin.video.afl-video#2641]
Hi...I don't  have the link in live matches for the current  Richmond Carlton match.... any idea why?

**Comment by 24Clayton** [comment]
I don't have it either, just disappeared

**Comment by parallelandy** [comment]
Likewise. AFL.TV is live but the current games in not. Very odd.

**Comment by glennguy** [comment]
On it now guys.
Changes on telstra/afls side... again...

**Comment by hawksta** [comment]
Thanks Glen...

**Comment by pinheadmercs** [comment]
As always. Thanks for all your help

**Comment by glennguy** [comment]
2.0.4 is now in both repositorys.

To force Kodi to check for the update - In the default (estuary) skin:

Go into Add-ons -> go into the 'open box' icon -> install from repository -> highlight our repo and bring up the context menu (long press, 'c', or right click) and select 'Check for updates'

Let me know how it goes!

**Comment by hawksta** [comment]
Excellent.... working perfectly... thanks once again

**Comment by 24Clayton** [comment]
Thank you Glenn, and thanks for all your efforts and hard work

**Comment by glennguy** [comment]
Happy to help, thanks for using the addon and bringing this to our attention!
